# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:7.5.0

pipelines:
  branches:
    master:
      - step:
          name: Upload to S3
          deployment: production # set to test, staging or production
          image: atlassian/pipelines-awscli
          script:
            - aws deploy push --application-name $APPLICATION_NAME --s3-location s3://$S3_BUCKET/prod --ignore-hidden-files
            - aws deploy create-deployment --application-name $APPLICATION_NAME --s3-location bucket=$S3_BUCKET,key=prod,bundleType=zip --deployment-group-name $DEPLOYMENT_GROUP_NAME
    development:
      - step:
          name: Upload to S3
          deployment: test # set to test, staging or production
          image: atlassian/pipelines-awscli
          script:
            - aws deploy push --application-name $APPLICATION_NAME_DEV --s3-location s3://$S3_BUCKET/webDev --ignore-hidden-files
            - aws deploy create-deployment --application-name $APPLICATION_NAME_DEV --s3-location bucket=$S3_BUCKET,key=webDev,bundleType=zip --deployment-group-name $DEPLOYMENT_GROUP_NAME_DEV
    
