# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  branches:
      master:
        - step:
            name: Build Application
            caches:
              - node
            script:
              - echo "Building and Deploying the master branch."
              # - npm install -- NOT SURE I NEED TO DO THIS
              # - npm run build -- DITTO
        - step:
            name: Deploy to S3
            deployment: production   # set to test, staging or production
            # trigger: manual  # uncomment to have a manual step
            image: atlassian/pipelines-awscli
            script:
              - echo "Deploying to AWS S3"
              - aws s3 sync --delete . s3://$S3_BUCKET

            


