# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        name: Deploy to AWS EC2
        deployment: production
        # trigger: manual  # uncomment to have a manual step
        image: atlassian/pipelines-awscli
        script:
          - aws deploy push --application-name <application-name> --s3-location s3://<S3 bucket>/<s3-key> --ignore-hidden-files
          - aws deploy create-deployment --application-name <application-name> --s3-location bucket=<s3-bucket>,key=<s3-key>,bundleType=zip --deployment-group-name <deployment-group>

        caches:
          - node

